config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  namespace :users do
    resources :restaurants
  end

  resources :restaurants, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :restaurants
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :restaurants, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/users/restaurants_controller.rb
class Users::RestaurantsController < ApplicationController
  def index
    @restaurants = current_user.restaurants.order(created_at: :desc)
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    if @restaurant.save
      redirect_to users_restaurants_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
  end

  def destroy
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantesHotwire</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/restaurants/_restaurant.html.erb
	<div class="col-4">
    <div class="product-card">
      <div class="product-details">
        <span class="product-catagory"></span>
        <h4><a href=""><%= restaurant.name %></a></h4>
        <p><%= restaurant.description %></p>
        <div class="product-bottom-details">
          <div class="product-price"><small><%= rand(10..28) %></small><%= rand(23..2345) %></div>
          <div class="product-links">
            <a href=""><i class="fa fa-heart"></i></a>
            <a href=""><i class="fa fa-shopping-cart"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
      <%= render @restaurants %>
  </div>
</div>

app/views/restaurants/show.html.erb
<h1>Restaurants#show</h1>
<p>Find me in app/views/restaurants/show.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Restaurants", restaurants_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/restaurants/_form.html.erb
<div class="container shadow mt-5 bg-white p-4">
  <%= simple_form_for [:users, @restaurant] do |f| %>
    <%= f.input :name  %>
    <%= f.input :address  %>
    <%= f.input :phone  %>
    <%= f.submit @restaurant.new_record? ? "Guardar" : "Actualizar", class: "btn btn-primary" %> <%= link_to "Volver", users_restaurants_path, class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/users/restaurants/_restaurant.erb
    <tr>
      <td> <%= restaurant.name %> </td>
      <td> <%= restaurant.address %> </td>
      <td> <%= restaurant.phone %></td>
      <td>
        <%= link_to edit_users_restaurant_path(restaurant) do %>
          <i class="fa-solid fa-pen-to-square text-warning"></i>
        <% end %>
        |
        <%= link_to users_restaurant_path(restaurant) do %>
          <i class="fa-solid fa-trash text-danger"></i>
        <% end %>
      </td>
    </tr>

app/views/users/restaurants/edit.html.erb
<%= render "form" %>

app/views/users/restaurants/index.html.erb
<div class="mt-4 d-flex justifiy-content-between ">
  <h3>Restaurants</h3>
  <div>
    <%= link_to "Nuevo", new_users_restaurant_path, class: "btn btn-success mx-4", data: {turbo_frame: "form_restaurant" } %>
  </div>

  <%= turbo_frame_tag "form_restaurant" %>


</div>
<hr>
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Dirección</th>
        <th>Telefóno</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
          <%= render @restaurants %>
    </tbody>
  </table>
</div>

app/views/users/restaurants/new.html.erb
  <%= render "form" %>

app/views/users/restaurants/show.html.erb
<h1>Users::Restaurants#show</h1>
<p>Find me in app/views/users/restaurants/show.html.erb</p>